MARGIN = 0
MINIMUM_DIGIT_SIZE = 100
IMAGE_HEIGHT = 200
IMAGE_WIDTH = 700
MASK_THRESHOLD = 0.5
SR = 2 # rows of cells
SC = 7 # columns of cells
B = 1  # bounding boxes per cell
C = 10 # digit classifier